sudo: required
services:
  - docker
env: 
  global: 
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

# Download Google SDK
before_install: 
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl    #install kubectl in Google
  - gcloud auth activate-service-account --key-file service-account.json    # authorize activate auth for credential
  - gcloud config set project multi-k8s-363102      # set G project ID
  - gcloud config set compute/zone asia-southeast1  # set location
  - gcloud container clusters get-credentials multi-cluster # set cluster name
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin     #Docker login
  - docker build -t bwan109/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bwan109/react-test npm test -- --coverage

deploy: 
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master